### ISSUE TITLE
Замечания #2

### ISSUE THREAD

**Issue by sergey-shambir** [oMystique/IIP#2]
- В конструктор Entity и его наследников передаётся слишком много параметров, надо использовать типы sf::Vector2f и sf::FloatRect для уменьшения их количества. Типовые поля x, y, w, h можно сжать до 1-2 полей геометрических типов данных.
- Цикл в World::InteractObjects следует избавить от итераторов, заменив их на range based for со ссылкой на элемент списка: http://en.cppreference.com/w/cpp/language/range-for
- чтобы не писать `(*it)->getRect().intersects((*at)->getRect())`, можно в классе Entity завести функцию Intersects (или DoesHit), которая сама извлечёт прямоугольники.
- конструкцию вида `distance = sqrt((player->x - (*it)->x)*(player->x - (*it)->x) + (player->y - (*it)->y)*(player->y - (*it)->y));` тоже следует сократить за счёт создания функции `GetDistance(Entity &, Entity &)`
- отдельные части World::InteractObjects (например, атака врагом видимого им игрока) можно вынести в отдельные приватные методы.

**Comment by oMystique** [comment]
Исправлено.
